CREATE TABLE Livre (id SERIAL PRIMARY KEY NOT NULL, Titre VARCHAR(255) NOT NULL, Résumé VARCHAR(255) NOT NULL, Année INTEGER NOT NULL, Série INTEGER, Genre INTEGER NOT NULL, Auteur INTEGER, Edition INTEGER);

CREATE TABLE Série (id SERIAL PRIMARY KEY NOT NULL, Nom VARCHAR(255) NOT NULL);

CREATE TABLE Genre (id SERIAL PRIMARY KEY NOT NULL, Nom VARCHAR(255) NOT NULL);

CREATE TABLE Auteur (id SERIAL PRIMARY KEY NOT NULL, Nom VARCHAR(255) NOT NULL);

CREATE TABLE Edition (id SERIAL PRIMARY KEY NOT NULL, Nom VARCHAR(255) NOT NULL, Année INTEGER NOT NULL, ISBN VARCHAR(13) NOT NULL, Editeur INTEGER NOT NULL, Exemplaire INTEGER NOT NULL);

CREATE TABLE Editeur (id SERIAL PRIMARY KEY NOT NULL, Nom VARCHAR(255) NOT NULL);

CREATE TABLE Exemplaire (id SERIAL PRIMARY KEY NOT NULL, Etat VARCHAR(20) NOT NULL, CHECK (etat IN ('Très bon', 'Bon', 'Mauvais')), Ami INTEGER NOT NULL);

CREATE TABLE Ami (id SERIAL PRIMARY KEY NOT NULL, Nom VARCHAR(255) NOT NULL, Téléphone VARCHAR(10) NOT NULL, Ecole VARCHAR(255) NOT NULL);

CREATE TABLE LivreAuteur (idLivre  INTEGER NOT NULL,idAuteur INTEGER NOT NULL, PRIMARY KEY (idLivre, idAuteur));

CREATE TABLE LivreGenre (idLivre  INTEGER NOT NULL,idGenre INTEGER NOT NULL, PRIMARY KEY (idLivre, idGenre));